<?php
/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2018 SalesAgility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for technical reasons, the Appropriate Legal Notices must
 * display the words "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 */
$relationships = array (
  'veta_recibo_spay_schedule_payment_company_1' => 
  array (
    'id' => '12de0a61-5e9e-5f43-1b58-62b2329ff1d6',
    'relationship_name' => 'veta_recibo_spay_schedule_payment_company_1',
    'lhs_module' => 'Veta_Recibo',
    'lhs_table' => 'veta_recibo',
    'lhs_key' => 'id',
    'rhs_module' => 'Spay_Schedule_Payment_Company',
    'rhs_table' => 'spay_schedule_payment_company',
    'rhs_key' => 'id',
    'join_table' => 'veta_recibo_spay_schedule_payment_company_1_c',
    'join_key_lhs' => 'veta_recibo_spay_schedule_payment_company_1veta_recibo_ida',
    'join_key_rhs' => 'veta_recib0cd7company_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'veta_recibo_spay_schedule_payment_applicant_1' => 
  array (
    'id' => '152a01e0-f1f2-69d4-d128-62b232515ac6',
    'relationship_name' => 'veta_recibo_spay_schedule_payment_applicant_1',
    'lhs_module' => 'Veta_Recibo',
    'lhs_table' => 'veta_recibo',
    'lhs_key' => 'id',
    'rhs_module' => 'Spay_Schedule_Payment_Applicant',
    'rhs_table' => 'spay_schedule_payment_applicant',
    'rhs_key' => 'id',
    'join_table' => 'veta_recibo_spay_schedule_payment_applicant_1_c',
    'join_key_lhs' => 'veta_recibo_spay_schedule_payment_applicant_1veta_recibo_ida',
    'join_key_rhs' => 'veta_recib5ff0plicant_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'veta_abono_veta_recibo' => 
  array (
    'id' => '214b696e-49b1-1187-19cf-62b232b46349',
    'relationship_name' => 'veta_abono_veta_recibo',
    'lhs_module' => 'Veta_Recibo',
    'lhs_table' => 'veta_recibo',
    'lhs_key' => 'id',
    'rhs_module' => 'Veta_Abono',
    'rhs_table' => 'veta_abono',
    'rhs_key' => 'id',
    'join_table' => 'veta_abono_veta_recibo_c',
    'join_key_lhs' => 'veta_abono_veta_reciboveta_recibo_ida',
    'join_key_rhs' => 'veta_abono_veta_reciboveta_abono_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'veta_recibo_opportunities' => 
  array (
    'id' => '271826b6-21fe-87ff-c608-62b232250ef9',
    'relationship_name' => 'veta_recibo_opportunities',
    'lhs_module' => 'Veta_Recibo',
    'lhs_table' => 'veta_recibo',
    'lhs_key' => 'id',
    'rhs_module' => 'Opportunities',
    'rhs_table' => 'opportunities',
    'rhs_key' => 'id',
    'join_table' => 'veta_recibo_opportunities_c',
    'join_key_lhs' => 'veta_recibo_opportunitiesveta_recibo_ida',
    'join_key_rhs' => 'veta_recibo_opportunitiesopportunities_idb',
    'relationship_type' => 'one-to-one',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'veta_requerimiento_veta_recibo' => 
  array (
    'id' => '3a8cf1d5-6ba6-871e-074f-62b232e2591c',
    'relationship_name' => 'veta_requerimiento_veta_recibo',
    'lhs_module' => 'Veta_Requerimiento',
    'lhs_table' => 'veta_requerimiento',
    'lhs_key' => 'id',
    'rhs_module' => 'Veta_Recibo',
    'rhs_table' => 'veta_recibo',
    'rhs_key' => 'id',
    'join_table' => 'veta_requerimiento_veta_recibo_c',
    'join_key_lhs' => 'veta_requerimiento_veta_reciboveta_requerimiento_ida',
    'join_key_rhs' => 'veta_requerimiento_veta_reciboveta_recibo_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'veta_recibo_veta_college_1' => 
  array (
    'id' => '3c883a94-b78c-d2c4-6118-62b23286a253',
    'relationship_name' => 'veta_recibo_veta_college_1',
    'lhs_module' => 'Veta_Recibo',
    'lhs_table' => 'veta_recibo',
    'lhs_key' => 'id',
    'rhs_module' => 'Veta_College',
    'rhs_table' => 'veta_college',
    'rhs_key' => 'id',
    'join_table' => 'veta_recibo_veta_college_1_c',
    'join_key_lhs' => 'veta_recibo_veta_college_1veta_recibo_ida',
    'join_key_rhs' => 'veta_recibo_veta_college_1veta_college_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'veta_recibo_contacts' => 
  array (
    'id' => '41847f5f-a9b2-aac5-dd9f-62b23266b280',
    'relationship_name' => 'veta_recibo_contacts',
    'lhs_module' => 'Contacts',
    'lhs_table' => 'contacts',
    'lhs_key' => 'id',
    'rhs_module' => 'Veta_Recibo',
    'rhs_table' => 'veta_recibo',
    'rhs_key' => 'id',
    'join_table' => 'veta_recibo_contacts_c',
    'join_key_lhs' => 'veta_recibo_contactscontacts_ida',
    'join_key_rhs' => 'veta_recibo_contactsveta_recibo_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'veta_recibo_nvc_deposit_company_1' => 
  array (
    'id' => '499d3d56-c328-287f-4b24-62b232b54de5',
    'relationship_name' => 'veta_recibo_nvc_deposit_company_1',
    'lhs_module' => 'Veta_Recibo',
    'lhs_table' => 'veta_recibo',
    'lhs_key' => 'id',
    'rhs_module' => 'NVC_Deposit_company',
    'rhs_table' => 'nvc_deposit_company',
    'rhs_key' => 'id',
    'join_table' => 'veta_recibo_nvc_deposit_company_1_c',
    'join_key_lhs' => 'veta_recibo_nvc_deposit_company_1veta_recibo_ida',
    'join_key_rhs' => 'veta_recibo_nvc_deposit_company_1nvc_deposit_company_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'veta_detallerecibo_veta_recibo' => 
  array (
    'id' => '4f534261-e308-4f00-4eb3-62b232cf92b7',
    'relationship_name' => 'veta_detallerecibo_veta_recibo',
    'lhs_module' => 'Veta_Recibo',
    'lhs_table' => 'veta_recibo',
    'lhs_key' => 'id',
    'rhs_module' => 'Veta_DetalleRecibo',
    'rhs_table' => 'veta_detallerecibo',
    'rhs_key' => 'id',
    'join_table' => 'veta_detallerecibo_veta_recibo_c',
    'join_key_lhs' => 'veta_detallerecibo_veta_reciboveta_recibo_ida',
    'join_key_rhs' => 'veta_detallerecibo_veta_reciboveta_detallerecibo_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'veta_recibo_leads' => 
  array (
    'id' => '525f5d3c-6b60-2c94-20b8-62b23239f288',
    'relationship_name' => 'veta_recibo_leads',
    'lhs_module' => 'Leads',
    'lhs_table' => 'leads',
    'lhs_key' => 'id',
    'rhs_module' => 'Veta_Recibo',
    'rhs_table' => 'veta_recibo',
    'rhs_key' => 'id',
    'join_table' => 'veta_recibo_leads_c',
    'join_key_lhs' => 'veta_recibo_leadsleads_ida',
    'join_key_rhs' => 'veta_recibo_leadsveta_recibo_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'veta_recibo_veta_presupuesto' => 
  array (
    'id' => '54dbcc4e-e6c7-cb37-17ba-62b23278d84a',
    'relationship_name' => 'veta_recibo_veta_presupuesto',
    'lhs_module' => 'Veta_Presupuesto',
    'lhs_table' => 'veta_presupuesto',
    'lhs_key' => 'id',
    'rhs_module' => 'Veta_Recibo',
    'rhs_table' => 'veta_recibo',
    'rhs_key' => 'id',
    'join_table' => 'veta_recibo_veta_presupuesto_c',
    'join_key_lhs' => 'veta_recibo_veta_presupuestoveta_presupuesto_ida',
    'join_key_rhs' => 'veta_recibo_veta_presupuestoveta_recibo_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'veta_recibo_emails' => 
  array (
    'id' => '5beb0601-31c8-5fba-1f56-62b232b2fe11',
    'relationship_name' => 'veta_recibo_emails',
    'lhs_module' => 'Veta_Recibo',
    'lhs_table' => 'veta_recibo',
    'lhs_key' => 'id',
    'rhs_module' => 'Emails',
    'rhs_table' => 'emails',
    'rhs_key' => 'id',
    'join_table' => 'veta_recibo_emails_c',
    'join_key_lhs' => 'veta_recibo_emailsveta_recibo_ida',
    'join_key_rhs' => 'veta_recibo_emailsemails_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'ForQueues',
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'veta_recibo_modified_user' => 
  array (
    'id' => '928c5ae5-05f0-57f1-2eed-62b232021f31',
    'relationship_name' => 'veta_recibo_modified_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Veta_Recibo',
    'rhs_table' => 'veta_recibo',
    'rhs_key' => 'modified_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'veta_recibo_created_by' => 
  array (
    'id' => '9360abde-4c09-a18a-646c-62b232540726',
    'relationship_name' => 'veta_recibo_created_by',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Veta_Recibo',
    'rhs_table' => 'veta_recibo',
    'rhs_key' => 'created_by',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'veta_recibo_assigned_user' => 
  array (
    'id' => '93af87d2-d213-9f95-2774-62b232de54b8',
    'relationship_name' => 'veta_recibo_assigned_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Veta_Recibo',
    'rhs_table' => 'veta_recibo',
    'rhs_key' => 'assigned_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'securitygroups_veta_recibo' => 
  array (
    'id' => '943e10cc-defa-abb2-7146-62b232fb22b7',
    'relationship_name' => 'securitygroups_veta_recibo',
    'lhs_module' => 'SecurityGroups',
    'lhs_table' => 'securitygroups',
    'lhs_key' => 'id',
    'rhs_module' => 'Veta_Recibo',
    'rhs_table' => 'veta_recibo',
    'rhs_key' => 'id',
    'join_table' => 'securitygroups_records',
    'join_key_lhs' => 'securitygroup_id',
    'join_key_rhs' => 'record_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'module',
    'relationship_role_column_value' => 'Veta_Recibo',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'veta_detallereciboitem_veta_recibo' => 
  array (
    'id' => 'e6360132-aaf8-b19e-471d-62b2321c4c3a',
    'relationship_name' => 'veta_detallereciboitem_veta_recibo',
    'lhs_module' => 'Veta_Recibo',
    'lhs_table' => 'veta_recibo',
    'lhs_key' => 'id',
    'rhs_module' => 'Veta_DetalleReciboItem',
    'rhs_table' => 'veta_detallereciboitem',
    'rhs_key' => 'id',
    'join_table' => 'veta_detallereciboitem_veta_recibo_c',
    'join_key_lhs' => 'veta_detallereciboitem_veta_reciboveta_recibo_ida',
    'join_key_rhs' => 'veta_detallereciboitem_veta_reciboveta_detallereciboitem_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'veta_recibo_conta_refunds_1' => 
  array (
    'rhs_label' => 'Refunds',
    'lhs_label' => 'Billing Statement',
    'rhs_subpanel' => 'default',
    'lhs_module' => 'Veta_Recibo',
    'rhs_module' => 'Conta_refunds',
    'relationship_type' => 'one-to-many',
    'readonly' => true,
    'deleted' => false,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
    'relationship_name' => 'veta_recibo_conta_refunds_1',
  ),
);