<?php

class Veta_RequerimientoViewDetail extends ViewDetail
{
    public function __construct()
    {
        parent::__construct();
    }

    public function display()
    {
        $this->load_lead_info();
        $this->load_contact_info();
        $this->load_semaforizacion();

        load_notes($this->bean, 'Veta_Requerimiento', 'virtual_all_notes');

        $this->ss->assign("TELCASA", $this->TELCASA);
        $this->ss->assign('CELULAR', $this->CELULAR);
        $this->ss->assign('PASAPORTE', $this->PASAPORTE);
        $this->ss->assign('EMAIL', $this->EMAIL);
        // $this->show_profile_button();
        parent::display();
    }
    public function load_semaforizacion()
    {
        switch ($this->bean->estado_semaforizacion_c) {
            case 'Verde':
                $color = '#0fcf15';
                break;
            case 'Amarillo':
                $color = '#ebb212';
                break;
            case 'Rojo':
                $color = '#d66c60';
                break;

            default:
                $color = '#0fcf15';
                break;
        }

        $this->bean->estado_semaforizacion_c = $color;


        $detalle = json_decode(htmlspecialchars_decode($this->bean->detalle_semaforizacion_c));
        // $this->bean->detalle_semaforizacion_c = '';

        if (is_null($detalle) || !count($detalle)) {
            $this->bean->detalle_semaforizacion_c = '';
            return;
        }

        $detalleDict = [
            'ticket' => 'Ticket <a href="/index.php?module=Auto_Tickets&action=DetailView&record={{id}}">{{name}}</a> pending',
            'documentos' => 'Documents without check ',
            'inmediato' => 'Immediate without contact',
            'potencial' => 'Potential without contact',
            'next' => 'Next Contact date expired',
            'abono' => '2 days after deposit without contact',
        ];
        $this->bean->detalle_semaforizacion_c = '<ul>';

        foreach ($detalle as $key => $value) {
            [$detalle_item, $id] = explode('_', $key);

            $str = $detalleDict[$detalle_item];
            if ($detalle_item == 'ticket') {
                $ticket = new Auto_Tickets();
                $ticket->retrieve($id);
                $str = str_replace('{{name}}', $ticket->name, str_replace('{{id}}', $ticket->id, $str));
            }

            $this->bean->detalle_semaforizacion_c .= "<li>$str</li>";
        }

        $this->bean->detalle_semaforizacion_c .= '</ul>';
        // $this->bean->estado_semaforizacion_c = "<div style='width: 20px;height: 20px;background: $color;border-radius: 50%;margin: auto;'></div>";

    }
    public function process()
    {
        parent::process(); // TODO: Change the autogenerated stub
    }

    public function _displaySubPanels()
    {
        $this->bean->email1 = $this->EMAIL;
        $this->bean->name =  $this->NOMBRE;
        parent::_displaySubPanels(); // TODO: Change the autogenerated stub
    }

    public function show_profile_button()
    {
        global $current_user;
        $profile = $this->bean->get_linked_beans('veta_profile_veta_requerimiento')[0];
        if ($profile || $current_user->id !== 'c5da6f79-e3de-2d8f-f42b-60d6505f50c2') return;

        // $this->bean->veta_profile_veta_requerimiento_name = "<input 
        // title=\"Fill Profile\" 
        // class=\"button\" 
        // onclick=\"var _form = document.getElementById('form_SubpanelQuickCreate_Veta_Profile');
        //  disableOnUnloadEditView(_form);
        //  _form.return_action.value='DetailView';
        //  _form.action.value='EditView';
        //  if(typeof(_form.to_pdf)!='undefined') _form.to_pdf.value='0';
        // \" 
        // type=\"submit\" 
        // name=\"Veta_Profile_subpanel_full_form_button\" 
        // id=\"Veta_Profile_subpanel_full_form_button\" 
        // value=\"Fill Profile\">";
    }


    /**
     * Carga información adicional que tiene como origen el prospecto
     */
    private function load_lead_info()
    {
        $query = "SELECT leads.id AS ID, 
                    CONCAT(leads.first_name, ' ' , leads.last_name) AS NOMBRE,
                    CONCAT(asignado.first_name, ' ', asignado.last_name) AS ASIGNADO,
                    TRIM(UPPER(asignado.address_city)) AS OFICINA,
                    leads.phone_home as TELCASA,
                    leads.phone_mobile as CELULAR,
                    leads_cstm.fecha_expiracion_visa_c AS FECHAEXPIRACIONVISA,
                    leads_cstm.expiracion_visa_c AS FECHAEXPIRACIONVISATEXTO,
                    leads_cstm.edad_c AS EDAD,
                    leads.date_modified AS FECHAMODIFICACION,
                    if(leads.converted = 1, \"YES\", \"NO\" )AS CONVERTIDO,
                    leads.status AS ESTADO,
                    leads.lead_source AS FUENTE,
                    leads_cstm.pais_c AS PAIS,
                    leads_cstm.departamento_c AS DPTO,
                    leads_cstm.ciudad_c AS CIUDAD,
                    leads_cstm.visa_c AS VISA,
                    leads_cstm.pasaporte_c AS PASAPORTE,
                    leads_cstm.ciudad_tmp_c AS CIUDADTMP,
                    leads_cstm.carrera_universitaria_c AS CARRERAUNIVERSITARIA,
                    leads_cstm.trabajo_actual_c AS TRABAJOACTUAL,
                    campaigns.name as CAMPANA                    
                FROM leads 
                INNER JOIN leads_cstm ON leads_cstm.id_c = leads.id 
                INNER JOIN veta_requerimiento_leads_c ON veta_requerimiento_leads_c.veta_requerimiento_leadsleads_ida = leads.id AND veta_requerimiento_leads_c.deleted = 0 
                INNER JOIN veta_requerimiento ON veta_requerimiento.id = veta_requerimiento_leads_c.veta_requerimiento_leadsveta_requerimiento_idb                
                LEFT JOIN users asignado ON asignado.id = leads.assigned_user_id AND asignado.deleted = 0
                LEFT JOIN campaigns ON campaigns.id = leads.campaign_id AND campaigns.deleted = 0 
                WHERE veta_requerimiento.deleted = 0 AND veta_requerimiento.id = '" . $this->bean->id . "'";

        $result = $this->bean->db->query(
            $query,
            true,
            "Error obteniendo informacion del prospecto asociado al requerimiento " . $this->bean->id
        );
        $row = $this->bean->db->fetchByAssoc($result);

        if ($row != null) {
            $lead = new Lead();
            $lead->retrieve($row['ID']);

            $this->TELCASA = $row['TELCASA'];
            $this->CELULAR = $row['CELULAR'];
            $this->PASAPORTE = $row['PASAPORTE'];
            $this->EMAIL = $lead->email1;
            $this->NOMBRE = $row['NOMBRE'];
        }
    }

    private function load_contact_info()
    {
        $query = "SELECT contacts.id AS ID, 
                    CONCAT(contacts.first_name, ' ' , contacts.last_name) AS NOMBRE,
                    CONCAT(asignado.first_name, ' ', asignado.last_name) AS ASIGNADO,
                    TRIM(UPPER(asignado.address_city)) AS OFICINA,
                    contacts.phone_home AS TELCASA,
                    contacts.phone_mobile AS CELULAR,
                    contacts.lead_source AS FUENTE,
                    contacts_cstm.pais_c AS PAIS,
                    contacts_cstm.departamento_c AS DEPARTAMENTO,
                    contacts_cstm.ciudad_c AS CIUDAD,     
                    contacts_cstm.fecha_expiracion_visa_c AS FECHAEXPIRACIONVISA,
                    contacts.date_modified AS FECHAMODIFICACION,
                    contacts_cstm.visa_c AS VISA,
                    contacts_cstm.carrera_universitaria_c AS CARRERAUNIVERSITARIA,
                    contacts_cstm.trabajo_actual_c AS TRABAJOACTUAL,
                    contacts_cstm.pasaporte_c AS PASAPORTE,
                    campaigns.name as CAMPANA                                   
                FROM contacts 
                INNER JOIN contacts_cstm ON contacts_cstm.id_c = contacts.id 
                INNER JOIN veta_requerimiento_contacts_c ON veta_requerimiento_contacts_c.veta_requerimiento_contactscontacts_ida = contacts.id AND veta_requerimiento_contacts_c.deleted = 0 
                INNER JOIN veta_requerimiento ON veta_requerimiento.id = veta_requerimiento_contacts_c.veta_requerimiento_contactsveta_requerimiento_idb                
                LEFT JOIN users asignado ON asignado.id = contacts.assigned_user_id AND asignado.deleted = 0
                LEFT JOIN campaigns ON campaigns.id = contacts.campaign_id AND campaigns.deleted = 0 
                 WHERE veta_requerimiento.deleted = 0 AND veta_requerimiento.id = '" . $this->bean->id . "'";

        $result = $this->bean->db->query(
            $query,
            true,
            "Error obteniendo informacion del contacto asociado al requerimiento " . $this->bean->id
        );
        $row = $this->bean->db->fetchByAssoc($result);

        if ($row != null) {
            $contact = new Contact();
            $contact->retrieve($row['ID']);

            $this->TELCASA = empty($this->TELCASA) ? $row['TELCASA'] : $this->TELCASA;
            $this->CELULAR = empty($this->CELULAR) ? $row['CELULAR'] : $this->CELULAR;
            $this->PASAPORTE = empty($this->PASAPORTE) ? $row['PASAPORTE'] : $this->PASAPORTE;
            $this->EMAIL = empty($this->EMAIL) ? $contact->email1 : $this->EMAIL;
            $this->NOMBRE = $row['NOMBRE'];
        }
    }
}
