<?php
/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2018 SalesAgility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for technical reasons, the Appropriate Legal Notices must
 * display the words "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 */
$relationships = array (
  'auto_tickets_modified_user' => 
  array (
    'id' => '6f50339e-761f-daa5-e0bc-669534568473',
    'relationship_name' => 'auto_tickets_modified_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Auto_Tickets',
    'rhs_table' => 'auto_tickets',
    'rhs_key' => 'modified_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
  ),
  'auto_tickets_created_by' => 
  array (
    'id' => '70619756-2879-14b9-f338-66953484b757',
    'relationship_name' => 'auto_tickets_created_by',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Auto_Tickets',
    'rhs_table' => 'auto_tickets',
    'rhs_key' => 'created_by',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
  ),
  'auto_tickets_assigned_user' => 
  array (
    'id' => '71832a66-9a5f-c350-91f0-669534a24e07',
    'relationship_name' => 'auto_tickets_assigned_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Auto_Tickets',
    'rhs_table' => 'auto_tickets',
    'rhs_key' => 'assigned_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
  ),
  'securitygroups_auto_tickets' => 
  array (
    'id' => '7271b9f5-bd1a-fb81-088a-669534479d86',
    'relationship_name' => 'securitygroups_auto_tickets',
    'lhs_module' => 'SecurityGroups',
    'lhs_table' => 'securitygroups',
    'lhs_key' => 'id',
    'rhs_module' => 'Auto_Tickets',
    'rhs_table' => 'auto_tickets',
    'rhs_key' => 'id',
    'join_table' => 'securitygroups_records',
    'join_key_lhs' => 'securitygroup_id',
    'join_key_rhs' => 'record_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'module',
    'relationship_role_column_value' => 'Auto_Tickets',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
  ),
  'auto_tickets_emails' => 
  array (
    'id' => '73c5f139-ac4a-da23-a781-669534c81379',
    'relationship_name' => 'auto_tickets_emails',
    'lhs_module' => 'Auto_Tickets',
    'lhs_table' => 'auto_tickets',
    'lhs_key' => 'id',
    'rhs_module' => 'Emails',
    'rhs_table' => 'emails',
    'rhs_key' => 'id',
    'join_table' => 'auto_tickets_emails_c',
    'join_key_lhs' => 'auto_tickets_emailsauto_tickets_ida',
    'join_key_rhs' => 'auto_tickets_emailsemails_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'ForQueues',
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => false,
  ),
  'auto_tickets_opportunities' => 
  array (
    'id' => '8794de29-0661-62a5-e586-669534dea416',
    'relationship_name' => 'auto_tickets_opportunities',
    'lhs_module' => 'Opportunities',
    'lhs_table' => 'opportunities',
    'lhs_key' => 'id',
    'rhs_module' => 'Auto_Tickets',
    'rhs_table' => 'auto_tickets',
    'rhs_key' => 'id',
    'join_table' => 'auto_tickets_opportunities_c',
    'join_key_lhs' => 'auto_tickets_opportunitiesopportunities_ida',
    'join_key_rhs' => 'auto_tickets_opportunitiesauto_tickets_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => false,
  ),
  'auto_tickets_veta_serviciocliente' => 
  array (
    'id' => '8d486831-ba65-82e1-6b18-669534c00bc5',
    'relationship_name' => 'auto_tickets_veta_serviciocliente',
    'lhs_module' => 'Veta_ServicioCliente',
    'lhs_table' => 'veta_serviciocliente',
    'lhs_key' => 'id',
    'rhs_module' => 'Auto_Tickets',
    'rhs_table' => 'auto_tickets',
    'rhs_key' => 'id',
    'join_table' => 'auto_tickets_veta_serviciocliente_c',
    'join_key_lhs' => 'auto_tickets_veta_servicioclienteveta_serviciocliente_ida',
    'join_key_rhs' => 'auto_tickets_veta_servicioclienteauto_tickets_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => false,
  ),
  'auto_tickets_veta_presupuesto' => 
  array (
    'id' => '9b8644ad-30c0-1352-231a-669534b8a065',
    'relationship_name' => 'auto_tickets_veta_presupuesto',
    'lhs_module' => 'Veta_Presupuesto',
    'lhs_table' => 'veta_presupuesto',
    'lhs_key' => 'id',
    'rhs_module' => 'Auto_Tickets',
    'rhs_table' => 'auto_tickets',
    'rhs_key' => 'id',
    'join_table' => 'auto_tickets_veta_presupuesto_c',
    'join_key_lhs' => 'auto_tickets_veta_presupuestoveta_presupuesto_ida',
    'join_key_rhs' => 'auto_tickets_veta_presupuestoauto_tickets_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => false,
  ),
  'auto_tickets_veta_recibo' => 
  array (
    'id' => 'c67136ff-1b7b-ca34-f3d1-669534383807',
    'relationship_name' => 'auto_tickets_veta_recibo',
    'lhs_module' => 'Veta_Recibo',
    'lhs_table' => 'veta_recibo',
    'lhs_key' => 'id',
    'rhs_module' => 'Auto_Tickets',
    'rhs_table' => 'auto_tickets',
    'rhs_key' => 'id',
    'join_table' => 'auto_tickets_veta_recibo_c',
    'join_key_lhs' => 'auto_tickets_veta_reciboveta_recibo_ida',
    'join_key_rhs' => 'auto_tickets_veta_reciboauto_tickets_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => false,
  ),
  'auto_tickets_veta_requerimiento' => 
  array (
    'id' => 'ced0be03-49e6-86b1-74cf-669534584816',
    'relationship_name' => 'auto_tickets_veta_requerimiento',
    'lhs_module' => 'Veta_Requerimiento',
    'lhs_table' => 'veta_requerimiento',
    'lhs_key' => 'id',
    'rhs_module' => 'Auto_Tickets',
    'rhs_table' => 'auto_tickets',
    'rhs_key' => 'id',
    'join_table' => 'auto_tickets_veta_requerimiento_c',
    'join_key_lhs' => 'auto_tickets_veta_requerimientoveta_requerimiento_ida',
    'join_key_rhs' => 'auto_tickets_veta_requerimientoauto_tickets_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => false,
  ),
  'auto_tickets_calls_1' => 
  array (
    'rhs_label' => 'Calls',
    'lhs_label' => 'Tickets',
    'rhs_subpanel' => 'default',
    'lhs_module' => 'Auto_Tickets',
    'rhs_module' => 'Calls',
    'relationship_type' => 'one-to-many',
    'readonly' => false,
    'deleted' => false,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
    'relationship_name' => 'auto_tickets_calls_1',
  ),
);