<?php
if (!defined('sugarEntry')) {
  define('sugarEntry', true);
}
include 'include/MVC/preDispatch.php';
$startTime = microtime(true);
require_once 'include/entryPoint.php';
ob_start();
require_once 'include/MVC/SugarApplication.php';


global $sugar_config, $session_id, $db;

$admin = new Administration();
$admin->retrieveSettings();


$baseConfig = array(
  'searchFormTab' => 'advanced_search',
  'query' => 'true',
  'name_advanced' => '',
  'virtual_lead_email_c_advanced' => '',
  'virtual_lead_phone_c_advanced' => '',
  'leap_id_advanced' => '',
  'company_leap_id_c_advanced' => '',
  'virtual_visa_exp_date_c_advanced_range_choice' => '=',
  'range_virtual_visa_exp_date_c_advanced' => '',
  'start_range_virtual_visa_exp_date_c_advanced' => '',
  'end_range_virtual_visa_exp_date_c_advanced' => '',
  'visa_expectation_date_c_advanced_range_choice' => '=',
  'range_visa_expectation_date_c_advanced' => '',
  'start_range_visa_expectation_date_c_advanced' => '',
  'end_range_visa_expectation_date_c_advanced' => '',
  'checklist_sent_date_c_advanced_range_choice' => '=',
  'range_checklist_sent_date_c_advanced' => '',
  'start_range_checklist_sent_date_c_advanced' => '',
  'end_range_checklist_sent_date_c_advanced' => '',
  'company_checklist_sent_date_c_advanced_range_choice' => '=',
  'range_company_checklist_sent_date_c_advanced' => '',
  'start_range_company_checklist_sent_date_c_advanced' => '',
  'end_range_company_checklist_sent_date_c_advanced' => '',
  'fecha_cierre_c_advanced_range_choice' => 'greater_than',
  'range_fecha_cierre_c_advanced' => '2020-01-01',
  'start_range_fecha_cierre_c_advanced' => '',
  'end_range_fecha_cierre_c_advanced' => '',
  'closing_date_company_c_advanced_range_choice' => '=',
  'range_closing_date_company_c_advanced' => '',
  'start_range_closing_date_company_c_advanced' => '',
  'end_range_closing_date_company_c_advanced' => '',
  'closing_date_applicant_c_advanced_range_choice' => '=',
  'range_closing_date_applicant_c_advanced' => '',
  'start_range_closing_date_applicant_c_advanced' => '',
  'end_range_closing_date_applicant_c_advanced' => '',
  'contacts_opportunities_1_name_advanced' => '',
  'leads_opportunities_1_name_advanced' => '',
  'case_manager_c_advanced' => '',
  'asignado_servicio_cliente_c_advanced' => '',
  'asignado_visas_c_advanced' => '',
  'estado_servicio_al_cliente_c_advanced' =>
  array(
    0 => 'Preparacion_Embajada',
    1 => 'SBS_And_Nomination_Checklist',
    2 => 'Checklist_Consultation_Sent',
    3 => 'Collecting_Documents',
    4 => 'Nomination_Checklist_Sent',
    5 => 'SBS_Checklist_Sent',
    6 => 'Revisado',
    7 => 'Visa',
    8 => 'Process_Requested',
    9 => 'Process_Lodge',
    10 => 'Process_Incompleted',
  ),
  'estado_visas_c_advanced' =>
  array(
    0 => 'Pendiente_Luz_Verde',
    1 => 'HAP_ID_Solicitar',
    2 => 'Draft_Done',
    3 => 'Draft_Incomplete',
    4 => 'Lodge_Requested',
    5 => 'Lodge_Incompleted',
    6 => 'Process_Draft_Requested',
    7 => 'Process_Draft_Incompleted',
    8 => 'Process_Draft_Done',
    9 => 'Process_Lodge_Requested',
    10 => 'Process_Lodge_Incompleted',
    11 => 'Process_Lodged',
    12 => 'Process_Lodge_Docs_Incompleted',
  ),
  'industry_aplicant_advanced' => '',
  'aplicant_first_payment_amount_advanced' => '',
  'profession_advanced' => '',
  'current_visa_subclass_advanced' => '',
  'current_job_position_advanced' => '',
  'month_of_experience_advanced' => '',
  'level_of_english_advanced' => '',
  'nationality_advanced' => '',
  'potential_visa_subclass_advanced' => '',
  'cost_agrement_number_advanced' => '',
  'cost_agrement_visa_subclass_advanced' => '',
  'migration_agent_name_advanced' => '',
  'recluter_name_advanced' => '',
  'company_name_advanced' => '',
  'company_city_advanced' => '',
  'company_industry_advanced' => '',
  'email_company_advanced' => '',
  'phone_company_advanced' => '',
  'company_first_payment_amount_advanced' => '',
  'secondary_aplicant_name_advanced' => '',
  'secondary_pasport_number_advanced' => '',
  'dependent_name_advanced' => '',
  'aplicant_mmm_fee_advanced' => '',
  'second_dependent_name_advanced' => '',
  'third_dependent_name_advanced' => '',
  'consultation_fee_advanced' => '',
  'aplicant_departments_visa_fee_advanced' => '',
  'company_mmm_fee_advanced' => '',
  'aplicant_company_mmm_advanced' => '',
  'total_advanced' => '',
  'aplicant_company_mmm_fees_advanced' => '',
  'total_paid_advanced' => '',
  'ocupation_advanced' => '',
  'main_aplicant_name_advanced' => '',
  'fecha_ultimo_contacto_c_advanced_range_choice' => '=',
  'range_fecha_ultimo_contacto_c_advanced' => '',
  'start_range_fecha_ultimo_contacto_c_advanced' => '',
  'end_range_fecha_ultimo_contacto_c_advanced' => '',
  'fecha_proximo_contacto_c_advanced_range_choice' => '=',
  'range_fecha_proximo_contacto_c_advanced' => '',
  'start_range_fecha_proximo_contacto_c_advanced' => '',
  'end_range_fecha_proximo_contacto_c_advanced' => '',
  'next_contact_date_company_c_advanced_range_choice' => '=',
  'range_next_contact_date_company_c_advanced' => '',
  'start_range_next_contact_date_company_c_advanced' => '',
  'end_range_next_contact_date_company_c_advanced' => '',
  'fecha_aplicacion_visa_c_advanced_range_choice' => '=',
  'range_fecha_aplicacion_visa_c_advanced' => '',
  'start_range_fecha_aplicacion_visa_c_advanced' => '',
  'end_range_fecha_aplicacion_visa_c_advanced' => '',
  'date_entered_advanced_range_choice' => '=',
  'range_date_entered_advanced' => '',
  'start_range_date_entered_advanced' => '',
  'end_range_date_entered_advanced' => '',
  'soel_fecha_expiracion_visa_advanced_range_choice' => '=',
  'range_soel_fecha_expiracion_visa_advanced' => '',
  'start_range_soel_fecha_expiracion_visa_advanced' => '',
  'end_range_soel_fecha_expiracion_visa_advanced' => '',
  'soel_visto_bueno_comercial_advanced' => '',
  'soel_visto_bueno_visas_advanced' => '',
  'soel_referido_advanced' => '',
  'soel_date_estudiante_advanced_range_choice' => '=',
  'range_soel_date_estudiante_advanced' => '',
  'start_range_soel_date_estudiante_advanced' => '',
  'end_range_soel_date_estudiante_advanced' => '',
  'soel_date_asesor_advanced_range_choice' => '=',
  'range_soel_date_asesor_advanced' => '',
  'start_range_soel_date_asesor_advanced' => '',
  'end_range_soel_date_asesor_advanced' => '',
  'soel_docs_solicitados_advanced' => '',
  'soel_docs_pendientes_advanced' => '',
  'consultation_date_advanced_range_choice' => '=',
  'range_consultation_date_advanced' => '',
  'start_range_consultation_date_advanced' => '',
  'end_range_consultation_date_advanced' => '',
  'aplicant_1st_payment_date_advanced_range_choice' => '=',
  'range_aplicant_1st_payment_date_advanced' => '',
  'start_range_aplicant_1st_payment_date_advanced' => '',
  'end_range_aplicant_1st_payment_date_advanced' => '',
  'quote_date_advanced_range_choice' => '=',
  'range_quote_date_advanced' => '',
  'start_range_quote_date_advanced' => '',
  'end_range_quote_date_advanced' => '',
  'company_1st_payment_date_advanced_range_choice' => '=',
  'range_company_1st_payment_date_advanced' => '',
  'start_range_company_1st_payment_date_advanced' => '',
  'end_range_company_1st_payment_date_advanced' => '',
  'company_sbs_expiry_date_advanced_range_choice' => '=',
  'range_company_sbs_expiry_date_advanced' => '',
  'start_range_company_sbs_expiry_date_advanced' => '',
  'end_range_company_sbs_expiry_date_advanced' => '',
  'secondary_dob_advanced' => '',
  'dependent_dob_advanced' => '',
  'second_dependent_dob_advanced' => '',
  'recruitment_expectation_date_c_advanced_range_choice' => '=',
  'range_recruitment_expectation_date_c_advanced' => '',
  'start_range_recruitment_expectation_date_c_advanced' => '',
  'end_range_recruitment_expectation_date_c_advanced' => '',
  'skill_assessment_app_expectation_date_c_advanced_range_choice' => '=',
  'range_skill_assessment_app_expectation_date_c_advanced' => '',
  'start_range_skill_assessment_app_expectation_date_c_advanced' => '',
  'end_range_skill_assessment_app_expectation_date_c_advanced' => '',
  'skill_assessment_app_date_visa_c_advanced_range_choice' => '=',
  'range_skill_assessment_app_date_visa_c_advanced' => '',
  'start_range_skill_assessment_app_date_visa_c_advanced' => '',
  'end_range_skill_assessment_app_date_visa_c_advanced' => '',
  'fecha_req1_c_advanced_range_choice' => '=',
  'range_fecha_req1_c_advanced' => '',
  'start_range_fecha_req1_c_advanced' => '',
  'end_range_fecha_req1_c_advanced' => '',
  'fecha_exp_req1_c_advanced_range_choice' => '=',
  'range_fecha_exp_req1_c_advanced' => '',
  'start_range_fecha_exp_req1_c_advanced' => '',
  'end_range_fecha_exp_req1_c_advanced' => '',
  'fecha_response_req1_c_advanced_range_choice' => '=',
  'range_fecha_response_req1_c_advanced' => '',
  'start_range_fecha_response_req1_c_advanced' => '',
  'end_range_fecha_response_req1_c_advanced' => '',
  'fecha_req2_c_advanced_range_choice' => '=',
  'range_fecha_req2_c_advanced' => '',
  'start_range_fecha_req2_c_advanced' => '',
  'end_range_fecha_req2_c_advanced' => '',
  'fecha_exp_req2_c_advanced_range_choice' => '=',
  'range_fecha_exp_req2_c_advanced' => '',
  'start_range_fecha_exp_req2_c_advanced' => '',
  'end_range_fecha_exp_req2_c_advanced' => '',
  'fecha_response_req2_c_advanced_range_choice' => '=',
  'range_fecha_response_req2_c_advanced' => '',
  'start_range_fecha_response_req2_c_advanced' => '',
  'end_range_fecha_response_req2_c_advanced' => '',
  'fecha_req3_c_advanced_range_choice' => '=',
  'range_fecha_req3_c_advanced' => '',
  'start_range_fecha_req3_c_advanced' => '',
  'end_range_fecha_req3_c_advanced' => '',
  'fecha_exp_req3_c_advanced_range_choice' => '=',
  'range_fecha_exp_req3_c_advanced' => '',
  'start_range_fecha_exp_req3_c_advanced' => '',
  'end_range_fecha_exp_req3_c_advanced' => '',
  'fecha_response_req3_c_advanced_range_choice' => '=',
  'range_fecha_response_req3_c_advanced' => '',
  'start_range_fecha_response_req3_c_advanced' => '',
  'end_range_fecha_response_req3_c_advanced' => '',
  'fecha_req4_c_advanced_range_choice' => '=',
  'range_fecha_req4_c_advanced' => '',
  'start_range_fecha_req4_c_advanced' => '',
  'end_range_fecha_req4_c_advanced' => '',
  'fecha_exp_req4_c_advanced_range_choice' => '=',
  'range_fecha_exp_req4_c_advanced' => '',
  'start_range_fecha_exp_req4_c_advanced' => '',
  'end_range_fecha_exp_req4_c_advanced' => '',
  'fecha_response_req4_c_advanced_range_choice' => '=',
  'range_fecha_response_req4_c_advanced' => '',
  'start_range_fecha_response_req4_c_advanced' => '',
  'end_range_fecha_response_req4_c_advanced' => '',
  'fecha_req5_c_advanced_range_choice' => '=',
  'range_fecha_req5_c_advanced' => '',
  'start_range_fecha_req5_c_advanced' => '',
  'end_range_fecha_req5_c_advanced' => '',
  'fecha_exp_req5_c_advanced_range_choice' => '=',
  'range_fecha_exp_req5_c_advanced' => '',
  'start_range_fecha_exp_req5_c_advanced' => '',
  'end_range_fecha_exp_req5_c_advanced' => '',
  'fecha_response_req5_c_advanced_range_choice' => '=',
  'range_fecha_response_req5_c_advanced' => '',
  'start_range_fecha_response_req5_c_advanced' => '',
  'end_range_fecha_response_req5_c_advanced' => '',
  'nomination_app_date_visa_c_advanced_range_choice' => '=',
  'range_nomination_app_date_visa_c_advanced' => '',
  'start_range_nomination_app_date_visa_c_advanced' => '',
  'end_range_nomination_app_date_visa_c_advanced' => '',
  'nomination_approval_date_c_advanced_range_choice' => '=',
  'range_nomination_approval_date_c_advanced' => '',
  'start_range_nomination_approval_date_c_advanced' => '',
  'end_range_nomination_approval_date_c_advanced' => '',
  'lmt_start_date_c_advanced_range_choice' => '=',
  'range_lmt_start_date_c_advanced' => '',
  'start_range_lmt_start_date_c_advanced' => '',
  'end_range_lmt_start_date_c_advanced' => '',
  'lmt_expectation_date_c_advanced_range_choice' => '=',
  'range_lmt_expectation_date_c_advanced' => '',
  'start_range_lmt_expectation_date_c_advanced' => '',
  'end_range_lmt_expectation_date_c_advanced' => '',
  'tas_application_date_c_advanced_range_choice' => '=',
  'range_tas_application_date_c_advanced' => '',
  'start_range_tas_application_date_c_advanced' => '',
  'end_range_tas_application_date_c_advanced' => '',
  'tas_expectation_date_c_advanced_range_choice' => '=',
  'range_tas_expectation_date_c_advanced' => '',
  'start_range_tas_expectation_date_c_advanced' => '',
  'end_range_tas_expectation_date_c_advanced' => '',
  'tas_approval_date_c_advanced_range_choice' => '=',
  'range_tas_approval_date_c_advanced' => '',
  'start_range_tas_approval_date_c_advanced' => '',
  'end_range_tas_approval_date_c_advanced' => '',
  'rcb_application_date_c_advanced_range_choice' => '=',
  'range_rcb_application_date_c_advanced' => '',
  'start_range_rcb_application_date_c_advanced' => '',
  'end_range_rcb_application_date_c_advanced' => '',
  'rcb_expectation_date_c_advanced_range_choice' => '=',
  'range_rcb_expectation_date_c_advanced' => '',
  'start_range_rcb_expectation_date_c_advanced' => '',
  'end_range_rcb_expectation_date_c_advanced' => '',
  'rcb_approval_date_c_advanced_range_choice' => '=',
  'range_rcb_approval_date_c_advanced' => '',
  'start_range_rcb_approval_date_c_advanced' => '',
  'end_range_rcb_approval_date_c_advanced' => '',
  'eoi_application_date_c_advanced_range_choice' => '=',
  'range_eoi_application_date_c_advanced' => '',
  'start_range_eoi_application_date_c_advanced' => '',
  'end_range_eoi_application_date_c_advanced' => '',
  'eoi_expectation_date_c_advanced_range_choice' => '=',
  'range_eoi_expectation_date_c_advanced' => '',
  'start_range_eoi_expectation_date_c_advanced' => '',
  'end_range_eoi_expectation_date_c_advanced' => '',
  'eoi_appoval_date_c_advanced_range_choice' => '=',
  'range_eoi_appoval_date_c_advanced' => '',
  'start_range_eoi_appoval_date_c_advanced' => '',
  'end_range_eoi_appoval_date_c_advanced' => '',
  'roi_application_date_c_advanced_range_choice' => '=',
  'range_roi_application_date_c_advanced' => '',
  'start_range_roi_application_date_c_advanced' => '',
  'end_range_roi_application_date_c_advanced' => '',
  'roi_expectation_date_c_advanced_range_choice' => '=',
  'range_roi_expectation_date_c_advanced' => '',
  'start_range_roi_expectation_date_c_advanced' => '',
  'end_range_roi_expectation_date_c_advanced' => '',
  'roi_approval_date_c_advanced_range_choice' => '=',
  'range_roi_approval_date_c_advanced' => '',
  'start_range_roi_approval_date_c_advanced' => '',
  'end_range_roi_approval_date_c_advanced' => '',
  'zero_payment_c_advanced' => '',
  'pending_payments_c_advanced' => '',
  'second_quarter_c_advanced' => '',
  'third_quarter_c_advanced' => '',
  'filter_uploaded_docs_c_advanced' => '',
  'search_module' => 'Opportunities',
  'saved_search_action' => 'update',
  'displayColumns' => 'NAME|VETA_RECIBO_OPPORTUNITIES_NAME|COST_AGREMENT_VISA_SUBCLASS|COMPANY_NAME|COMPANY_LEAP_ID_C|LEADS_OPPORTUNITIES_1_NAME|LEAP_ID|VIRTUAL_VISA_EXP_DATE_C|VISA_EXPECTATION_DATE_C|CURRENT_VISA_SUBCLASS|OCUPATION|CHECKLIST_SENT_DATE_C|COMPANY_CHECKLIST_SENT_DATE_C|VIRTUAL_LEAD_PHONE_C|CASE_MANAGER_C|ASIGNADO_SERVICIO_CLIENTE_C|ESTADO_SERVICIO_AL_CLIENTE_C|ESTADO_VISAS_C|FECHA_PROXIMO_CONTACTO_C|NEXT_CONTACT_DATE_COMPANY_C|SOEL_VISTO_BUENO_VISAS|DOCS_PORTAL_URL_C|APPLICANT_REQUESTED_DOCS_C|APPLICANT_UPLOADED_DOCS_C|APPLICANT_PENDING_DOCS_C|APPLICANT_APPROVED_DOCS_C|COMPANY_REQUESTED_DOCS_C|COMPANY_UPLOADED_DOCS_C|COMPANY_PENDING_DOCS_C|COMPANY_APPROVED_DOCS_C|SOEL_DATE_ESTUDIANTE|SOEL_DATE_ASESOR|VISA_EXPIRE_SECONDARY_APPLIC_C|VISA_EXPIRE_1ST_DEPENDENT_DA_C|VISA_EXPIRE_2ST_DEPENDENT_DA_C|VISA_EXPIRE_3ST_DEPENDENT_DA_C|COMPANY_SBS_EXPIRY_DATE|PHONE_COMPANY|FECHA_CIERRE_C|MIGRATION_AGENT_NAME|ASSIGNED_USER_NAME|ESTADO_GESTION_COMERCIAL_C|FECHA_APLICACION_VISA_C|CLOSING_DATE_APPLICANT_C|VISA_APP_DATE|SKILL_ASSESSMENT_APP_DATE_VISA_C|SKILL_ASSESSMENT_APP_EXPECTATION_DATE_C|NOMINATION_APP_DATE_VISA_C|NOMINATION_APP_EXPECTATION_DATE_C|NOMINATION_APPROVAL_DATE_C|LMT_START_DATE_C|LMT_EXPECTATION_DATE_C|TAS_APPLICATION_DATE_C|TAS_EXPECTATION_DATE_C|TAS_APPROVAL_DATE_C|EOI_EXPECTATION_DATE_C|EOI_APPLICATION_DATE_C|EOI_APPOVAL_DATE_C|ROI_APPLICATION_DATE_C|ROI_EXPECTATION_DATE_C|ROI_APPROVAL_DATE_C|RCB_APPLICATION_DATE_C|RCB_EXPECTATION_DATE_C|RCB_APPROVAL_DATE_C|APPLICANT_COMPANY_MMM_FEES_OUTSTANDING_AMOUNT_C|APPLICANT_COMPANY_OUTSTANDING_AMOUNT_C',
  'hideTabs' => 'SALES_STAGE|AMOUNT|LEAD_SOURCE|VIRTUAL_REQUERIMENT_C|CAMPAIGN_NAME|DATE_CLOSED|ASIGNADO_APLICACION_C|ASIGNADO_VISAS_C|ESTADO_ADMISIONES_C|ESTADO_PAGO_INSTITUCION_C|ESTADO_CARTERA_C|DATE_ENTERED|FECHA_PRESUPUESTO_C|SOEL_FECHA_VIAJE|SOEL_FECHA_EXPIRACION_VISA|CONTACTS_OPPORTUNITIES_1_NAME|SOEL_VISTO_BUENO_COMERCIAL|PROCESS_STAGES_C|SOEL_OFICINA|INDUSTRY_APLICANT|APPLICANT_INDUSTRY_C|CONSULTATION_DATE|APPLICANT_1ST_PAYMENT_DATE|APLICANT_FIRST_PAYMENT_AMOUNT|PROFESSION|CURRENT_JOB_POSITION|MONTHS_OF_EXPERIENCE|LEVEL_OF_ENGLISH|NATIONALITY|POTENTIAL_VISA_SUBCLASS|COST_AGREMENT_NUMBER|QUOTE_DATE|RECLUTER_NAME|COMPANY_CITY|COMPANY_INDUSTRY|EMAIL_COMPANY|COMPANY_1ST_PAYMENT_DATE|COMPANY_FIRST_PAYMENT_AMOUNT|SECONDARY_APLICANT_NAME|SECONDARY_PASPORT_NUMBER|SECONDARY_DOB|DEPENDENT_NAME|DEPENDENT_DOB|SECOND_DEPENDENT_NAME|SECOND_DEPENDENT_DOB|THIRD_DEPENDENT_NAME|APLICANT_DEPARTMENTS_VISA_FEE|COMPANY_MMM_FEE|APLICANT_COMPANY_MMM|APLICANT_COMPANY_MMM_FEES|TOTAL_PAID|MAIN_APLICANT_NAME|NOMINATION_APP_EXP_DATE|NOMINATION_APP_DATE|SKILL_ASSESSMENT_APP_EXP_DATE|SKILL_ASSESSMENT_APP_DATE|VIRTUAL_SBS_APPROVAL_DATE_C|VIRTUAL_SBS_EXPECTATION_DATE_C|VIRTUAL_TBS_APPROVAL_DATE_C|VIRTUAL_TBS_EXPECTATION_DATE_C|VIRTUAL_TBS_APPLICATION_DATE_C|VIRTUAL_LABOUR_APPLICATION_DATE_C|VIRTUAL_LABOUR_EXPECTATION_DATE_C|VIRTUAL_NOMINATION_APPROVAL_DATE_C|RECRUITMENT|RECRUITMENT_EXP_DATE|COMPANY_TOTAL_C|COMPANY_OUTSTANDING_AMOUNT_C|DISCOUNT|TOTAL_WITHOUT_GST|APLICANT_MMM_FEE|GST_PERCENTAGE|CONSULTATION_FEE|INSURANCE_VALUE|DEPARTMENT_VISA_FEE_BASE_APPLICATION_CHARGE|DEPARTMENT_CREDIT_CARD_SURCHARGE_PERCENTAGE|DEPOSIT|OUTSTANDING_AMOUNT|TOTAL|EMAIL_DOCS_PORTAL_C|SBS_PROCESS_STAGE_C|VIRTUAL_VISA_C|ROI_PROCESS_STAGE_C|EOI_PROCESS_STAGE_C|RCB_PROCESS_STAGE_C|TAS_PROCESS_STAGE_C|LMT_PROCESS_STAGE_C|NOMINATION_PROCESS_STAGE_C|SKILL_ASSESSMENT_PROCESS_STAGE_C|STATE_NOMINATION_PROCESS_STAGE_C|THIRD_QUARTER_MMM_FEES_PAID_COMPANY_C|FIRST_QUARTER_MMM_FEES_PAID_APPLICANT_C|THIRD_QUARTER_MMM_FEES_PAID_APPLICANT_C|THIRD_QUARTER_MMM_FEES_PAID_C|NVC_COMPANIES_OPPORTUNITIES_1_NAME|RFI_NAME_5_C|RFI_NAME_4_C|RFI_NAME_1_C|RFI_NAME_2_C|RFI_NAME_3_C|VIRTUAL_LEAD_EMAIL_C|APPLICANT_COMPANY_TOTAL_MMM_FEES_PAID_C|DATE_MODIFIED|CREATED_BY_NAME|SOEL_DOCS_APROBADOS|SOEL_DOCS_CARGADOS|SOEL_DOCS_PENDIENTES|MODIFIED_BY_NAME|PENDIENTE_PAGO_COLEGIOS_C|PENDIENTE_CARTERA_C|TOTAL_SKILL_ASSESSMENTE_APPLICANT_COMPANY_C|TOTAL_SKILL_ASSESSMENTE_APPLICANT_C|TOTAL_SKILL_ASSESSMENTE_COMPANY_C|APPLICANT_COMPANY_DEPARTMENT_CREDIT_CARD_SURCHARGE_C|FECHA_ULTIMO_CONTACTO_C|APPLICANT_COMPANY_DEPARTMENTS_VISA_FEE_C|APPLICANT_COMPANY_GST_C|APPLICANT_COMPANY_TOTAL_WITHOUT_GST_C|COMPANY_DEPARTMENTS_VISA_FEE_C|APPLICANT_COMPANY_DEPARTMENT_VISA_FEE_BASE_APPLICATION_CHARGE_C|SOEL_DOCS_SOLICITADOS|SOEL_REFERIDO|COMPANY_GST_C|COMPANY_TOTAL_WITHOUT_GST_C|COMPANY_LEAD_ID_C|COMPANY_DEPT_VISA_FEE_BASE_C|COMPANY_DEPT_CC_SURCHARGE_C|COMPANY_DISCOUNT_C|COMPANY_DEPOSITS_C|CLOSING_DATE_COMPANY_C|APPLICANT_COMPANY_TOTAL_PAID_C|APPLICANT_COMPANY_TOTAL_C|FECHA_REQ1_C|FECHA_EXP_REQ1_C|FECHA_RESPONSE_REQ1_C|FECHA_REQ2_C|FECHA_EXP_REQ2_C|FECHA_RESPONSE_REQ2_C|FECHA_REQ3_C|FECHA_EXP_REQ3_C|FECHA_RESPONSE_REQ4_C|FECHA_RESPONSE_REQ3_C|FECHA_REQ4_C|RFI_1_TYPES_C|FECHA_RESPONSE_REQ5_C|RFI_5_TYPES_C|RFI_2_TYPES_C|RFI_4_TYPES_C|FECHA_EXP_REQ5_C|RFI_3_TYPES_C|FECHA_REQ5_C|FECHA_EXP_REQ4_C',
  'orderBy' => 'VIRTUAL_VISA_EXP_DATE_C',
  'sortOrder' => 'ASC',
  'advanced' => true,
);

$query = "SELECT u.id,concat(u.first_name,' ',u.last_name) as full_name, ss.id as saved_search_id, ss.contents,ss.name
FROM users u 
JOIN users_cstm uc ON uc.id_c = u.id
LEFT JOIN saved_search ss ON u.id = ss.assigned_user_id AND ss.name like '%VOLUMEN - MMM%' AND ss.search_module = 'Opportunities'
WHERE uc.user_department_c = 'Case_Manager'
AND u.employee_status = 'Active'
";

$res = $db->query($query);

while ($row = $db->fetchByAssoc($res)) {
  $contents = $baseConfig;
  $contents['case_manager_c_advanced'] = $row['full_name'];
  // echo $contents['dashlets']['6cebb9d2-bef0-17a5-04c9-653be2547b81']['options']['filters']['created_by'] . "<br>";
  // echo "$updateQuery <br>";
  $contentsStr = base64_encode(serialize($contents));
  $values =( $row['saved_search_id'] ? "'" . $row['saved_search_id'] . "'" : 'uuid()' ). " , '" .( $row['name']?$row['name']:$row['full_name'].' VOLUMEN - MMM') . "' , 'Opportunities' , 0 , now(), now() , '" . $row['id'] . "' , '" . $contentsStr . "' ,''";
  // if ($row['preference_id']) {
  $updateQuery = "INSERT INTO saved_search (id, name, search_module, deleted, date_entered, date_modified, assigned_user_id, contents, description) 
    VALUES  ($values) ON DUPLICATE KEY UPDATE contents = VALUES(contents);  #" . $row['name'] ." | ".$row['full_name'];
  echo "$updateQuery <br>";
  // }
}
