<?php
/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2018 SalesAgility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for technical reasons, the Appropriate Legal Notices must
 * display the words "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 */

// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  0 => 
  array (
    'acceptable_sugar_versions' => 
    array (
      0 => '',
    ),
  ),
  1 => 
  array (
    'acceptable_sugar_flavors' => 
    array (
      0 => 'CE',
      1 => 'PRO',
      2 => 'ENT',
    ),
  ),
  'readme' => '',
  'key' => 'CSChe',
  'author' => 'Alfonso Lopez',
  'description' => '',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'Customer_Services_Checklist',
  'published_date' => '2023-03-08 18:39:15',
  'type' => 'module',
  'version' => 1678300755,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'Customer_Services_Checklist',
  'beans' => 
  array (
    0 => 
    array (
      'module' => 'CSChe_Items_Requested',
      'class' => 'CSChe_Items_Requested',
      'path' => 'modules/CSChe_Items_Requested/CSChe_Items_Requested.php',
      'tab' => true,
    ),
    1 => 
    array (
      'module' => 'CSChe_CS_Checklist',
      'class' => 'CSChe_CS_Checklist',
      'path' => 'modules/CSChe_CS_Checklist/CSChe_CS_Checklist.php',
      'tab' => true,
    ),
    2 => 
    array (
      'module' => 'CSChe_Items',
      'class' => 'CSChe_Items',
      'path' => 'modules/CSChe_Items/CSChe_Items.php',
      'tab' => true,
    ),
  ),
  'layoutdefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/csche_items_requested_veta_serviciocliente_Veta_ServicioCliente.php',
      'to_module' => 'Veta_ServicioCliente',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/csche_items_requested_veta_serviciocliente_CSChe_Items_Requested.php',
      'to_module' => 'CSChe_Items_Requested',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/csche_items_requested_csche_items_CSChe_Items.php',
      'to_module' => 'CSChe_Items',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/csche_items_requested_csche_items_CSChe_Items_Requested.php',
      'to_module' => 'CSChe_Items_Requested',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/csche_cs_checklist_csche_items_CSChe_Items.php',
      'to_module' => 'CSChe_Items',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/csche_cs_checklist_csche_items_CSChe_CS_Checklist.php',
      'to_module' => 'CSChe_CS_Checklist',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/csche_cs_checklist_veta_serviciocliente_Veta_ServicioCliente.php',
      'to_module' => 'Veta_ServicioCliente',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/csche_cs_checklist_veta_serviciocliente_CSChe_CS_Checklist.php',
      'to_module' => 'CSChe_CS_Checklist',
    ),
  ),
  'relationships' => 
  array (
    0 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/csche_items_requested_veta_servicioclienteMetaData.php',
    ),
    1 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/csche_items_requested_csche_itemsMetaData.php',
    ),
    2 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/csche_cs_checklist_csche_itemsMetaData.php',
    ),
    3 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/csche_cs_checklist_veta_servicioclienteMetaData.php',
    ),
  ),
  'image_dir' => '<basepath>/icons',
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/CSChe_Items_Requested',
      'to' => 'modules/CSChe_Items_Requested',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/modules/CSChe_CS_Checklist',
      'to' => 'modules/CSChe_CS_Checklist',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/modules/CSChe_Items',
      'to' => 'modules/CSChe_Items',
    ),
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_ServicioCliente.php',
      'to_module' => 'Veta_ServicioCliente',
      'language' => 'en_us',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_ServicioCliente.php',
      'to_module' => 'Veta_ServicioCliente',
      'language' => 'es_ES',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/CSChe_Items_Requested.php',
      'to_module' => 'CSChe_Items_Requested',
      'language' => 'en_us',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/CSChe_Items_Requested.php',
      'to_module' => 'CSChe_Items_Requested',
      'language' => 'es_ES',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/CSChe_Items.php',
      'to_module' => 'CSChe_Items',
      'language' => 'en_us',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/CSChe_Items.php',
      'to_module' => 'CSChe_Items',
      'language' => 'es_ES',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/CSChe_Items_Requested.php',
      'to_module' => 'CSChe_Items_Requested',
      'language' => 'en_us',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/CSChe_Items_Requested.php',
      'to_module' => 'CSChe_Items_Requested',
      'language' => 'es_ES',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/CSChe_Items.php',
      'to_module' => 'CSChe_Items',
      'language' => 'en_us',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/CSChe_Items.php',
      'to_module' => 'CSChe_Items',
      'language' => 'es_ES',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/CSChe_CS_Checklist.php',
      'to_module' => 'CSChe_CS_Checklist',
      'language' => 'en_us',
    ),
    11 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/CSChe_CS_Checklist.php',
      'to_module' => 'CSChe_CS_Checklist',
      'language' => 'es_ES',
    ),
    12 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_ServicioCliente.php',
      'to_module' => 'Veta_ServicioCliente',
      'language' => 'en_us',
    ),
    13 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_ServicioCliente.php',
      'to_module' => 'Veta_ServicioCliente',
      'language' => 'es_ES',
    ),
    14 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/CSChe_CS_Checklist.php',
      'to_module' => 'CSChe_CS_Checklist',
      'language' => 'en_us',
    ),
    15 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/CSChe_CS_Checklist.php',
      'to_module' => 'CSChe_CS_Checklist',
      'language' => 'es_ES',
    ),
    16 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/en_us.lang.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
  ),
  'vardefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/csche_items_requested_veta_serviciocliente_Veta_ServicioCliente.php',
      'to_module' => 'Veta_ServicioCliente',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/csche_items_requested_veta_serviciocliente_CSChe_Items_Requested.php',
      'to_module' => 'CSChe_Items_Requested',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/csche_items_requested_csche_items_CSChe_Items.php',
      'to_module' => 'CSChe_Items',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/csche_items_requested_csche_items_CSChe_Items_Requested.php',
      'to_module' => 'CSChe_Items_Requested',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/csche_cs_checklist_csche_items_CSChe_Items.php',
      'to_module' => 'CSChe_Items',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/csche_cs_checklist_csche_items_CSChe_CS_Checklist.php',
      'to_module' => 'CSChe_CS_Checklist',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/csche_cs_checklist_veta_serviciocliente_Veta_ServicioCliente.php',
      'to_module' => 'Veta_ServicioCliente',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/csche_cs_checklist_veta_serviciocliente_CSChe_CS_Checklist.php',
      'to_module' => 'CSChe_CS_Checklist',
    ),
  ),
);