<?php
/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2018 SalesAgility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for technical reasons, the Appropriate Legal Notices must
 * display the words "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 */
$relationships = array (
  'veta_detallepresupuesto_veta_presupuesto' => 
  array (
    'id' => '4c8d2e43-240e-44ed-7d17-6169a926088a',
    'relationship_name' => 'veta_detallepresupuesto_veta_presupuesto',
    'lhs_module' => 'Veta_Presupuesto',
    'lhs_table' => 'veta_presupuesto',
    'lhs_key' => 'id',
    'rhs_module' => 'Veta_DetallePresupuesto',
    'rhs_table' => 'veta_detallepresupuesto',
    'rhs_key' => 'id',
    'join_table' => 'veta_detallepresupuesto_veta_presupuesto_c',
    'join_key_lhs' => 'veta_detallepresupuesto_veta_presupuestoveta_presupuesto_ida',
    'join_key_rhs' => 'veta_detal7e03upuesto_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => false,
  ),
  'veta_presupuesto_contacts' => 
  array (
    'id' => '5ac14eaf-7e6d-ce0f-0410-6169a9acf145',
    'relationship_name' => 'veta_presupuesto_contacts',
    'lhs_module' => 'Contacts',
    'lhs_table' => 'contacts',
    'lhs_key' => 'id',
    'rhs_module' => 'Veta_Presupuesto',
    'rhs_table' => 'veta_presupuesto',
    'rhs_key' => 'id',
    'join_table' => 'veta_presupuesto_contacts_c',
    'join_key_lhs' => 'veta_presupuesto_contactscontacts_ida',
    'join_key_rhs' => 'veta_presupuesto_contactsveta_presupuesto_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => false,
  ),
  'veta_presupuesto_emails' => 
  array (
    'id' => '5b320897-048e-4734-9b55-6169a92580a1',
    'relationship_name' => 'veta_presupuesto_emails',
    'lhs_module' => 'Veta_Presupuesto',
    'lhs_table' => 'veta_presupuesto',
    'lhs_key' => 'id',
    'rhs_module' => 'Emails',
    'rhs_table' => 'emails',
    'rhs_key' => 'id',
    'join_table' => 'veta_presupuesto_emails_c',
    'join_key_lhs' => 'veta_presupuesto_emailsveta_presupuesto_ida',
    'join_key_rhs' => 'veta_presupuesto_emailsemails_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'ForQueues',
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => false,
  ),
  'veta_presupuesto_leads' => 
  array (
    'id' => '5b9b1dd3-e654-9c50-ac77-6169a9ada938',
    'relationship_name' => 'veta_presupuesto_leads',
    'lhs_module' => 'Leads',
    'lhs_table' => 'leads',
    'lhs_key' => 'id',
    'rhs_module' => 'Veta_Presupuesto',
    'rhs_table' => 'veta_presupuesto',
    'rhs_key' => 'id',
    'join_table' => 'veta_presupuesto_leads_c',
    'join_key_lhs' => 'veta_presupuesto_leadsleads_ida',
    'join_key_rhs' => 'veta_presupuesto_leadsveta_presupuesto_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => false,
  ),
  'veta_recibo_veta_presupuesto' => 
  array (
    'id' => '5d8657e8-66eb-8915-d8e9-6169a92883eb',
    'relationship_name' => 'veta_recibo_veta_presupuesto',
    'lhs_module' => 'Veta_Presupuesto',
    'lhs_table' => 'veta_presupuesto',
    'lhs_key' => 'id',
    'rhs_module' => 'Veta_Recibo',
    'rhs_table' => 'veta_recibo',
    'rhs_key' => 'id',
    'join_table' => 'veta_recibo_veta_presupuesto_c',
    'join_key_lhs' => 'veta_recibo_veta_presupuestoveta_presupuesto_ida',
    'join_key_rhs' => 'veta_recibo_veta_presupuestoveta_recibo_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => false,
  ),
  'veta_requerimiento_veta_presupuesto' => 
  array (
    'id' => '60c10fd5-edaa-fbe0-fc23-6169a9cfe324',
    'relationship_name' => 'veta_requerimiento_veta_presupuesto',
    'lhs_module' => 'Veta_Requerimiento',
    'lhs_table' => 'veta_requerimiento',
    'lhs_key' => 'id',
    'rhs_module' => 'Veta_Presupuesto',
    'rhs_table' => 'veta_presupuesto',
    'rhs_key' => 'id',
    'join_table' => 'veta_requerimiento_veta_presupuesto_c',
    'join_key_lhs' => 'veta_requerimiento_veta_presupuestoveta_requerimiento_ida',
    'join_key_rhs' => 'veta_requerimiento_veta_presupuestoveta_presupuesto_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => false,
  ),
  'veta_presupuesto_modified_user' => 
  array (
    'id' => 'd6daaa40-dfdb-5e10-1ed1-6169a9a5e7ae',
    'relationship_name' => 'veta_presupuesto_modified_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Veta_Presupuesto',
    'rhs_table' => 'veta_presupuesto',
    'rhs_key' => 'modified_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
  ),
  'veta_presupuesto_created_by' => 
  array (
    'id' => 'd758ee4f-b668-7b9f-2f84-6169a9d7bd52',
    'relationship_name' => 'veta_presupuesto_created_by',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Veta_Presupuesto',
    'rhs_table' => 'veta_presupuesto',
    'rhs_key' => 'created_by',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
  ),
  'veta_presupuesto_assigned_user' => 
  array (
    'id' => 'd7ce871e-cb56-8e4e-74f2-6169a9911ac0',
    'relationship_name' => 'veta_presupuesto_assigned_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Veta_Presupuesto',
    'rhs_table' => 'veta_presupuesto',
    'rhs_key' => 'assigned_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
  ),
  'securitygroups_veta_presupuesto' => 
  array (
    'id' => 'd831ff0f-60da-309e-b077-6169a9afa2e9',
    'relationship_name' => 'securitygroups_veta_presupuesto',
    'lhs_module' => 'SecurityGroups',
    'lhs_table' => 'securitygroups',
    'lhs_key' => 'id',
    'rhs_module' => 'Veta_Presupuesto',
    'rhs_table' => 'veta_presupuesto',
    'rhs_key' => 'id',
    'join_table' => 'securitygroups_records',
    'join_key_lhs' => 'securitygroup_id',
    'join_key_rhs' => 'record_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'module',
    'relationship_role_column_value' => 'Veta_Presupuesto',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
  ),
  'veta_presupuesto_veta_requerimiento_1' => 
  array (
    'lhs_module' => 'Veta_Presupuesto',
    'rhs_module' => 'Veta_Requerimiento',
    'relationship_type' => 'one-to-one',
    'readonly' => false,
    'deleted' => false,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => false,
    'relationship_name' => 'veta_presupuesto_veta_requerimiento_1',
  ),
);