<?php
/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2018 SalesAgility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for technical reasons, the Appropriate Legal Notices must
 * display the words "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 */

require_once( 'modules/Veta_Recibo/Veta_Recibo.php' );

class NVC_Deposit_company extends Basic
{
    public $new_schema = true;
    public $module_dir = 'NVC_Deposit_company';
    public $object_name = 'NVC_Deposit_company';
    public $table_name = 'nvc_deposit_company';
    public $importable = false;

    public $id;
    public $name;
    public $date_entered;
    public $date_modified;
    public $modified_user_id;
    public $modified_by_name;
    public $created_by;
    public $created_by_name;
    public $description;
    public $deleted;
    public $created_by_link;
    public $modified_user_link;
    public $assigned_user_id;
    public $assigned_user_name;
    public $assigned_user_link;
    public $SecurityGroups;
    public $deposit_amount;
    public $currency_id;
	
    public function bean_implements($interface)
    {
        switch($interface)
        {
            case 'ACL':
                return true;
        }

        return false;
    }    
	
	private function set_consecutivo()
    {
        if ( ! isset( $this->name ) || empty( $this->name ) )
        {
			$query  = "SELECT name as num FROM nvc_deposit_company order by date_entered desc limit 1";
            $result = $this->db->query( $query, true, "Error obteniendo el consecutivo del recibo" );
            $row    = $this->db->fetchByAssoc( $result );

            if ( $row != null )
            {
                $this->name = $row[ 'num' ] + 1;
            }			
        }
    }
	
	private function relacionar_estudiante()
    {
        $recibos = $this->get_linked_beans( 'veta_abono_veta_recibo', 'Veta_Recibo' );
		$recibos = $this->get_linked_beans( 'veta_recibo_nvc_deposit_company_1', 'Veta_Recibo' );		

        foreach ( $recibos as $recibo )
        {
            //$abonos = $recibo->get_linked_beans( 'veta_abono_veta_recibo', 'Veta_Abono' );
			$abonos = $recibo->get_linked_beans( 'veta_recibo_nvc_deposit_company_1', 'NVC_Deposit_company' );

            if ( count( $abonos ) == 1 )
            {
                $recibo->convertir_prospecto();
                $this->cerrar_requerimiento();
            }

        }
    }

    public function save( $check_notify = false )
    {

        $r = new Veta_Recibo();
		/* 
		if(($this->custom_date_entered_company_c != '') or ($this->custom_date_entered_company_c )) {
			$this->date_entered = $this->custom_date_entered_company_c;
			error_log("custom date - Alfonso company". $this->custom_date_entered_company_c);
		}
		*/

        if ( $r->is_gerente_contable() )
        {

            $this->set_consecutivo();
            $aux = parent::save( $check_notify ); // TODO: Change the autogenerated stub

            $r->id = $this->update_recibo();
            //$this->relacionar_estudiante();
			$this->cerrar_requerimiento();
			
			// Activar Workflow $r->new_opportunity($r->id);
			
			if($this->deposit_amount > 0){				
				
				$result = $r->new_opportunity( $r->id ); 
				
				if($result->id){ 				
					//$this->redireccionar('Workflow Created', $r->id);
					//error_log("Alfonso error - SI CREO WORKFLOW");
				} else {
					//error_log("Alfonso error - NO CREO WORKFLOW ENTRO No depisit");
					//$this->redireccionar('There is no deposit for this Invoice', $r->id);				
				}
			}
			
			
        }
        else
        {
            $r->redireccionar( 'Solo un gerente contable puede modificar un recibo', $r->id );
        }
    }
	
	/**
     * Establece el estado del requerimiento asociando como Cerrado debido a que se realizo un abono
     */
    private function cerrar_requerimiento()
    {
        $sql = "UPDATE veta_requerimiento_cstm 
                INNER JOIN veta_requerimiento_veta_presupuesto_c ON veta_requerimiento_veta_presupuesto_c.veta_requerimiento_veta_presupuestoveta_requerimiento_ida = veta_requerimiento_cstm.id_c AND veta_requerimiento_veta_presupuesto_c.deleted = 0 
                INNER JOIN veta_presupuesto ON veta_presupuesto.id = veta_requerimiento_veta_presupuesto_c.veta_requerimiento_veta_presupuestoveta_presupuesto_idb AND veta_presupuesto.deleted = 0 
                INNER JOIN veta_recibo_veta_presupuesto_c ON veta_recibo_veta_presupuesto_c.veta_recibo_veta_presupuestoveta_presupuesto_ida = veta_presupuesto.id AND veta_recibo_veta_presupuesto_c.deleted = 0 
                INNER JOIN veta_recibo ON veta_recibo.id = veta_recibo_veta_presupuesto_c.veta_recibo_veta_presupuestoveta_recibo_idb AND veta_recibo.deleted = 0 
                INNER JOIN veta_recibo_nvc_deposit_company_1_c ON veta_recibo_nvc_deposit_company_1_c.veta_recibo_nvc_deposit_company_1veta_recibo_ida = veta_recibo.id AND veta_recibo_nvc_deposit_company_1_c.deleted = 0 
                INNER JOIN nvc_deposit_company ON nvc_deposit_company.id = veta_recibo_nvc_deposit_company_1_c.veta_recibo_nvc_deposit_company_1nvc_deposit_company_idb AND nvc_deposit_company.deleted = 0
                SET company_stage_c = 'Cerrado'  
                WHERE nvc_deposit_company.id = '" . $this->id . "'";
				
				//company_stage_c

        $this->db->query( $sql );
    }

    private function update_recibo()
    {
        $id      = null;
        $recibos = $this->get_linked_beans( 'veta_recibo_nvc_deposit_company_1', 'NVC_Deposit_company' );

        foreach ( $recibos as $r )
        {
            $r->update_cartera();
			
			$oportunidades = $r->get_linked_beans( 'veta_recibo_opportunities', 'Opportunity' );

			foreach ( $oportunidades as $op )
			{
				$o = $op;
				error_log('ALFONSO - OPPORTUNIDAD - UPDATE RECIBO ' . $o->name);
			}
			
			if (isset ($o)) {
				$r->actualizar_oportunidad($o);
			}
			
            $id = $r->id;
        }

        return $id;
    }

    public function mark_deleted( $id )
    {
        $rec     = new Veta_Recibo();
        $recibos = $this->get_linked_beans( 'veta_recibo_nvc_deposit_company_1', 'NVC_Deposit_company' );

        if ( $rec->is_gerente_contable() )
        {
            parent::mark_deleted( $id ); // TODO: Change the autogenerated stub

            foreach ( $recibos as $r )
                $r->update_cartera();
				
				$oportunidades = $r->get_linked_beans( 'veta_recibo_opportunities', 'Opportunity' );

				foreach ( $oportunidades as $op )
				{
					$o = $op;
					error_log('ALFONSO - OPPORTUNIDAD - DELETE PAGO ' . $o->name);
				}
				
				$r->actualizar_oportunidad($o);
        }
        else
        {
            $this->redireccionar( 'Solo un gerente contable puede eliminar un recibo', $id );
        }
    }

    public function redireccionar( $msg, $registro )
    {
        if ( ! empty( $registro ) )
        {
            $aux = "<script>
                      var registro='" . $registro . "';";

            $aux .= "alert('" . $msg . "');
                    window.location = 'index.php?module=NVC_Deposit_Company&action=DetailView&record=' + registro;
                 </script>";

            echo $aux;
        }
        else
        {
            echo "<script>alert('" . $msg . "')</script>";
        }

        exit;
    }
	
	function deleteAttachment($isduplicate = "false")
    {
        if ($this->ACLAccess('edit')) {
            if ($isduplicate == "true") {
                return true;
            }
            $removeFile = "upload://{$this->id}";
        }

        if (file_exists($removeFile)) {
            if (!unlink($removeFile)) {
                $GLOBALS['log']->error("*** Could not unlink() file: [ {$removeFile} ]");
            } else {
                $this->uploadfile = '';
                $this->filename = '';
                $this->file_mime_type = '';
                $this->file = '';
                $this->save();
                return true;
            }
        } else {
            $this->uploadfile = '';
            $this->file_mime_type = '';
            $this->file = '';
            $this->save();
            return true;
        }
        return false;
    }
	
}
