<?php
/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2018 SalesAgility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for technical reasons, the Appropriate Legal Notices must
 * display the words "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 */

// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  0 => 
  array (
    'acceptable_sugar_versions' => 
    array (
      0 => '',
    ),
  ),
  1 => 
  array (
    'acceptable_sugar_flavors' => 
    array (
      0 => 'CE',
      1 => 'PRO',
      2 => 'ENT',
    ),
  ),
  'readme' => '',
  'key' => 'job',
  'author' => 'alopezh09',
  'description' => '',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'Job_Portal',
  'published_date' => '2022-11-19 00:04:16',
  'type' => 'module',
  'version' => 1668816256,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'Job_Portal',
  'beans' => 
  array (
    0 => 
    array (
      'module' => 'job_Categories',
      'class' => 'job_Categories',
      'path' => 'modules/job_Categories/job_Categories.php',
      'tab' => true,
    ),
    1 => 
    array (
      'module' => 'job_Jobs',
      'class' => 'job_Jobs',
      'path' => 'modules/job_Jobs/job_Jobs.php',
      'tab' => true,
    ),
    2 => 
    array (
      'module' => 'job_Messages',
      'class' => 'job_Messages',
      'path' => 'modules/job_Messages/job_Messages.php',
      'tab' => true,
    ),
  ),
  'layoutdefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/job_jobs_leads_Leads.php',
      'to_module' => 'Leads',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/job_jobs_leads_job_Jobs.php',
      'to_module' => 'job_Jobs',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/job_jobs_nvc_companies_NVC_Companies.php',
      'to_module' => 'NVC_Companies',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/job_messages_job_jobs_job_Jobs.php',
      'to_module' => 'job_Jobs',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/job_messages_job_jobs_job_Messages.php',
      'to_module' => 'job_Messages',
    ),
  ),
  'relationships' => 
  array (
    0 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/job_jobs_leadsMetaData.php',
    ),
    1 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/job_jobs_nvc_companiesMetaData.php',
    ),
    2 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/job_messages_job_jobsMetaData.php',
    ),
  ),
  'image_dir' => '<basepath>/icons',
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/job_Categories',
      'to' => 'modules/job_Categories',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/modules/job_Jobs',
      'to' => 'modules/job_Jobs',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/modules/job_Messages',
      'to' => 'modules/job_Messages',
    ),
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Leads.php',
      'to_module' => 'Leads',
      'language' => 'en_us',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Leads.php',
      'to_module' => 'Leads',
      'language' => 'es_ES',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/job_Jobs.php',
      'to_module' => 'job_Jobs',
      'language' => 'en_us',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/job_Jobs.php',
      'to_module' => 'job_Jobs',
      'language' => 'es_ES',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/job_Jobs.php',
      'to_module' => 'job_Jobs',
      'language' => 'en_us',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/job_Jobs.php',
      'to_module' => 'job_Jobs',
      'language' => 'es_ES',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/NVC_Companies.php',
      'to_module' => 'NVC_Companies',
      'language' => 'en_us',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/NVC_Companies.php',
      'to_module' => 'NVC_Companies',
      'language' => 'es_ES',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/job_Jobs.php',
      'to_module' => 'job_Jobs',
      'language' => 'en_us',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/job_Jobs.php',
      'to_module' => 'job_Jobs',
      'language' => 'es_ES',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/job_Messages.php',
      'to_module' => 'job_Messages',
      'language' => 'en_us',
    ),
    11 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/job_Messages.php',
      'to_module' => 'job_Messages',
      'language' => 'es_ES',
    ),
    12 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/en_us.lang.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
  ),
  'vardefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/job_jobs_leads_Leads.php',
      'to_module' => 'Leads',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/job_jobs_leads_job_Jobs.php',
      'to_module' => 'job_Jobs',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/job_jobs_nvc_companies_job_Jobs.php',
      'to_module' => 'job_Jobs',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/job_jobs_nvc_companies_NVC_Companies.php',
      'to_module' => 'NVC_Companies',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/job_messages_job_jobs_job_Jobs.php',
      'to_module' => 'job_Jobs',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/job_messages_job_jobs_job_Messages.php',
      'to_module' => 'job_Messages',
    ),
  ),
  'layoutfields' => 
  array (
    0 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
  ),
);