<?php
/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2018 SalesAgility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for technical reasons, the Appropriate Legal Notices must
 * display the words "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 */

// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  0 => 
  array (
    'acceptable_sugar_versions' => 
    array (
      0 => '',
    ),
  ),
  1 => 
  array (
    'acceptable_sugar_flavors' => 
    array (
      0 => 'CE',
      1 => 'PRO',
      2 => 'ENT',
    ),
  ),
  'readme' => '',
  'key' => 'Auto',
  'author' => '',
  'description' => '',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'Tickets',
  'published_date' => '2023-01-16 03:09:34',
  'type' => 'module',
  'version' => 1673838574,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'Tickets',
  'beans' => 
  array (
    0 => 
    array (
      'module' => 'Auto_Tickets',
      'class' => 'Auto_Tickets',
      'path' => 'modules/Auto_Tickets/Auto_Tickets.php',
      'tab' => true,
    ),
  ),
  'layoutdefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/auto_tickets_opportunities_Opportunities.php',
      'to_module' => 'Opportunities',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/auto_tickets_veta_requerimiento_Veta_Requerimiento.php',
      'to_module' => 'Veta_Requerimiento',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/auto_tickets_veta_presupuesto_Veta_Presupuesto.php',
      'to_module' => 'Veta_Presupuesto',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/auto_tickets_veta_recibo_Veta_Recibo.php',
      'to_module' => 'Veta_Recibo',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/auto_tickets_emails_Auto_Tickets.php',
      'to_module' => 'Auto_Tickets',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/auto_tickets_veta_serviciocliente_Veta_ServicioCliente.php',
      'to_module' => 'Veta_ServicioCliente',
    ),
  ),
  'relationships' => 
  array (
    0 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/auto_tickets_opportunitiesMetaData.php',
    ),
    1 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/auto_tickets_veta_requerimientoMetaData.php',
    ),
    2 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/auto_tickets_veta_presupuestoMetaData.php',
    ),
    3 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/auto_tickets_veta_reciboMetaData.php',
    ),
    4 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/auto_tickets_emailsMetaData.php',
    ),
    5 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/auto_tickets_veta_servicioclienteMetaData.php',
    ),
  ),
  'image_dir' => '<basepath>/icons',
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Auto_Tickets',
      'to' => 'modules/Auto_Tickets',
    ),
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Auto_Tickets.php',
      'to_module' => 'Auto_Tickets',
      'language' => 'en_us',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Auto_Tickets.php',
      'to_module' => 'Auto_Tickets',
      'language' => 'es_ES',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'en_us',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'es_ES',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Auto_Tickets.php',
      'to_module' => 'Auto_Tickets',
      'language' => 'en_us',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Auto_Tickets.php',
      'to_module' => 'Auto_Tickets',
      'language' => 'es_ES',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_Requerimiento.php',
      'to_module' => 'Veta_Requerimiento',
      'language' => 'en_us',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_Requerimiento.php',
      'to_module' => 'Veta_Requerimiento',
      'language' => 'es_ES',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Auto_Tickets.php',
      'to_module' => 'Auto_Tickets',
      'language' => 'en_us',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Auto_Tickets.php',
      'to_module' => 'Auto_Tickets',
      'language' => 'es_ES',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_Presupuesto.php',
      'to_module' => 'Veta_Presupuesto',
      'language' => 'en_us',
    ),
    11 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_Presupuesto.php',
      'to_module' => 'Veta_Presupuesto',
      'language' => 'es_ES',
    ),
    12 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Auto_Tickets.php',
      'to_module' => 'Auto_Tickets',
      'language' => 'en_us',
    ),
    13 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Auto_Tickets.php',
      'to_module' => 'Auto_Tickets',
      'language' => 'es_ES',
    ),
    14 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_Recibo.php',
      'to_module' => 'Veta_Recibo',
      'language' => 'en_us',
    ),
    15 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_Recibo.php',
      'to_module' => 'Veta_Recibo',
      'language' => 'es_ES',
    ),
    16 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Emails.php',
      'to_module' => 'Emails',
      'language' => 'en_us',
    ),
    17 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Emails.php',
      'to_module' => 'Emails',
      'language' => 'es_ES',
    ),
    18 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Auto_Tickets.php',
      'to_module' => 'Auto_Tickets',
      'language' => 'en_us',
    ),
    19 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Auto_Tickets.php',
      'to_module' => 'Auto_Tickets',
      'language' => 'es_ES',
    ),
    20 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Auto_Tickets.php',
      'to_module' => 'Auto_Tickets',
      'language' => 'en_us',
    ),
    21 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Auto_Tickets.php',
      'to_module' => 'Auto_Tickets',
      'language' => 'es_ES',
    ),
    22 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_ServicioCliente.php',
      'to_module' => 'Veta_ServicioCliente',
      'language' => 'en_us',
    ),
    23 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Veta_ServicioCliente.php',
      'to_module' => 'Veta_ServicioCliente',
      'language' => 'es_ES',
    ),
    24 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/en_us.lang.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
  ),
  'vardefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/auto_tickets_opportunities_Auto_Tickets.php',
      'to_module' => 'Auto_Tickets',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/auto_tickets_opportunities_Opportunities.php',
      'to_module' => 'Opportunities',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/auto_tickets_veta_requerimiento_Auto_Tickets.php',
      'to_module' => 'Auto_Tickets',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/auto_tickets_veta_requerimiento_Veta_Requerimiento.php',
      'to_module' => 'Veta_Requerimiento',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/auto_tickets_veta_presupuesto_Auto_Tickets.php',
      'to_module' => 'Auto_Tickets',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/auto_tickets_veta_presupuesto_Veta_Presupuesto.php',
      'to_module' => 'Veta_Presupuesto',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/auto_tickets_veta_recibo_Auto_Tickets.php',
      'to_module' => 'Auto_Tickets',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/auto_tickets_veta_recibo_Veta_Recibo.php',
      'to_module' => 'Veta_Recibo',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/auto_tickets_emails_Emails.php',
      'to_module' => 'Emails',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/auto_tickets_emails_Auto_Tickets.php',
      'to_module' => 'Auto_Tickets',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/auto_tickets_veta_serviciocliente_Auto_Tickets.php',
      'to_module' => 'Auto_Tickets',
    ),
    11 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/auto_tickets_veta_serviciocliente_Veta_ServicioCliente.php',
      'to_module' => 'Veta_ServicioCliente',
    ),
  ),
  'layoutfields' => 
  array (
    0 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    1 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    2 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    3 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    4 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    5 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
  ),
);