<?php

class Veta_EndorsementsViewEdit extends ViewEdit
{
    function preDisplay()
    {
        $this->bean->virtual_region_c = $this->bean->region_c;



        return parent::preDisplay(); // TODO: Change the autogenerated stub
    }
}
