<?php
/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2018 SalesAgility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for technical reasons, the Appropriate Legal Notices must
 * display the words "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 */
$relationships = array (
  'veta_requerimiento_doc_plantillas_1' => 
  array (
    'id' => '355a41c2-9cad-d3a7-a295-62029e74f98e',
    'relationship_name' => 'veta_requerimiento_doc_plantillas_1',
    'lhs_module' => 'Veta_Requerimiento',
    'lhs_table' => 'veta_requerimiento',
    'lhs_key' => 'id',
    'rhs_module' => 'Doc_Plantillas',
    'rhs_table' => 'doc_plantillas',
    'rhs_key' => 'id',
    'join_table' => 'veta_requerimiento_doc_plantillas_1_c',
    'join_key_lhs' => 'veta_requerimiento_doc_plantillas_1veta_requerimiento_ida',
    'join_key_rhs' => 'veta_requerimiento_doc_plantillas_1doc_plantillas_idb',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'veta_requerimiento_activities_1_calls' => 
  array (
    'id' => '38ce2c1c-80f4-65a6-7f23-62029e24f366',
    'relationship_name' => 'veta_requerimiento_activities_1_calls',
    'lhs_module' => 'Veta_Requerimiento',
    'lhs_table' => 'veta_requerimiento',
    'lhs_key' => 'id',
    'rhs_module' => 'Calls',
    'rhs_table' => 'calls',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Veta_Requerimiento',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'veta_requerimiento_doc_documentos_adic_1' => 
  array (
    'id' => '3c888631-33cf-cff4-b86e-62029eaffcef',
    'relationship_name' => 'veta_requerimiento_doc_documentos_adic_1',
    'lhs_module' => 'Veta_Requerimiento',
    'lhs_table' => 'veta_requerimiento',
    'lhs_key' => 'id',
    'rhs_module' => 'Doc_Documentos_Adic',
    'rhs_table' => 'doc_documentos_adic',
    'rhs_key' => 'id',
    'join_table' => 'veta_requerimiento_doc_documentos_adic_1_c',
    'join_key_lhs' => 'veta_requerimiento_doc_documentos_adic_1veta_requerimiento_ida',
    'join_key_rhs' => 'veta_requerimiento_doc_documentos_adic_1doc_documentos_adic_idb',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => 'default',
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'veta_requerimiento_leads' => 
  array (
    'id' => '3ccee199-ec44-2e23-efd1-62029e21e921',
    'relationship_name' => 'veta_requerimiento_leads',
    'lhs_module' => 'Leads',
    'lhs_table' => 'leads',
    'lhs_key' => 'id',
    'rhs_module' => 'Veta_Requerimiento',
    'rhs_table' => 'veta_requerimiento',
    'rhs_key' => 'id',
    'join_table' => 'veta_requerimiento_leads_c',
    'join_key_lhs' => 'veta_requerimiento_leadsleads_ida',
    'join_key_rhs' => 'veta_requerimiento_leadsveta_requerimiento_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'veta_requerimiento_activities_1_meetings' => 
  array (
    'id' => '4849f632-8e20-4727-aecf-62029e2894b9',
    'relationship_name' => 'veta_requerimiento_activities_1_meetings',
    'lhs_module' => 'Veta_Requerimiento',
    'lhs_table' => 'veta_requerimiento',
    'lhs_key' => 'id',
    'rhs_module' => 'Meetings',
    'rhs_table' => 'meetings',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Veta_Requerimiento',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'veta_requerimiento_activities_1_tasks' => 
  array (
    'id' => '4a151699-d5c6-e524-c3fa-62029ec6045e',
    'relationship_name' => 'veta_requerimiento_activities_1_tasks',
    'lhs_module' => 'Veta_Requerimiento',
    'lhs_table' => 'veta_requerimiento',
    'lhs_key' => 'id',
    'rhs_module' => 'Tasks',
    'rhs_table' => 'tasks',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Veta_Requerimiento',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'veta_requerimiento_contacts' => 
  array (
    'id' => '4c2e93c2-d14a-7ff9-6ccb-62029eed5a18',
    'relationship_name' => 'veta_requerimiento_contacts',
    'lhs_module' => 'Contacts',
    'lhs_table' => 'contacts',
    'lhs_key' => 'id',
    'rhs_module' => 'Veta_Requerimiento',
    'rhs_table' => 'veta_requerimiento',
    'rhs_key' => 'id',
    'join_table' => 'veta_requerimiento_contacts_c',
    'join_key_lhs' => 'veta_requerimiento_contactscontacts_ida',
    'join_key_rhs' => 'veta_requerimiento_contactsveta_requerimiento_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'veta_requerimiento_veta_recibo' => 
  array (
    'id' => '4e1e40d2-89a1-8c2e-0c78-62029e9bd92b',
    'relationship_name' => 'veta_requerimiento_veta_recibo',
    'lhs_module' => 'Veta_Requerimiento',
    'lhs_table' => 'veta_requerimiento',
    'lhs_key' => 'id',
    'rhs_module' => 'Veta_Recibo',
    'rhs_table' => 'veta_recibo',
    'rhs_key' => 'id',
    'join_table' => 'veta_requerimiento_veta_recibo_c',
    'join_key_lhs' => 'veta_requerimiento_veta_reciboveta_requerimiento_ida',
    'join_key_rhs' => 'veta_requerimiento_veta_reciboveta_recibo_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'veta_requerimiento_modified_user' => 
  array (
    'id' => '55870341-b9bb-5ba6-39c4-62029e032adc',
    'relationship_name' => 'veta_requerimiento_modified_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Veta_Requerimiento',
    'rhs_table' => 'veta_requerimiento',
    'rhs_key' => 'modified_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'veta_requerimiento_doc_docssolicitados_1' => 
  array (
    'id' => '55d8b086-6d24-c874-28d1-62029e6ba760',
    'relationship_name' => 'veta_requerimiento_doc_docssolicitados_1',
    'lhs_module' => 'Veta_Requerimiento',
    'lhs_table' => 'veta_requerimiento',
    'lhs_key' => 'id',
    'rhs_module' => 'Doc_DocsSolicitados',
    'rhs_table' => 'doc_docssolicitados',
    'rhs_key' => 'id',
    'join_table' => 'veta_requerimiento_doc_docssolicitados_1_c',
    'join_key_lhs' => 'veta_requerimiento_doc_docssolicitados_1veta_requerimiento_ida',
    'join_key_rhs' => 'veta_requerimiento_doc_docssolicitados_1doc_docssolicitados_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'nvc_companies_veta_requerimiento_1' => 
  array (
    'id' => '561ea1a4-9f2c-b178-e216-62029ed0c9f7',
    'relationship_name' => 'nvc_companies_veta_requerimiento_1',
    'lhs_module' => 'NVC_Companies',
    'lhs_table' => 'nvc_companies',
    'lhs_key' => 'id',
    'rhs_module' => 'Veta_Requerimiento',
    'rhs_table' => 'veta_requerimiento',
    'rhs_key' => 'id',
    'join_table' => 'nvc_companies_veta_requerimiento_1_c',
    'join_key_lhs' => 'nvc_companies_veta_requerimiento_1nvc_companies_ida',
    'join_key_rhs' => 'nvc_companies_veta_requerimiento_1veta_requerimiento_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'veta_requerimiento_activities_1_notes' => 
  array (
    'id' => '5acdd152-5b15-b493-c019-62029e26ac13',
    'relationship_name' => 'veta_requerimiento_activities_1_notes',
    'lhs_module' => 'Veta_Requerimiento',
    'lhs_table' => 'veta_requerimiento',
    'lhs_key' => 'id',
    'rhs_module' => 'Notes',
    'rhs_table' => 'notes',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Veta_Requerimiento',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'veta_requerimiento_veta_presupuesto' => 
  array (
    'id' => '5b1031e4-d2e7-6405-2145-62029e7c231d',
    'relationship_name' => 'veta_requerimiento_veta_presupuesto',
    'lhs_module' => 'Veta_Requerimiento',
    'lhs_table' => 'veta_requerimiento',
    'lhs_key' => 'id',
    'rhs_module' => 'Veta_Presupuesto',
    'rhs_table' => 'veta_presupuesto',
    'rhs_key' => 'id',
    'join_table' => 'veta_requerimiento_veta_presupuesto_c',
    'join_key_lhs' => 'veta_requerimiento_veta_presupuestoveta_requerimiento_ida',
    'join_key_rhs' => 'veta_requerimiento_veta_presupuestoveta_presupuesto_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'veta_requerimiento_activities_1_emails' => 
  array (
    'id' => '5c574e35-28f5-a244-7021-62029ef58cb6',
    'relationship_name' => 'veta_requerimiento_activities_1_emails',
    'lhs_module' => 'Veta_Requerimiento',
    'lhs_table' => 'veta_requerimiento',
    'lhs_key' => 'id',
    'rhs_module' => 'Emails',
    'rhs_table' => 'emails',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'Veta_Requerimiento',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'veta_requerimiento_created_by' => 
  array (
    'id' => '5e7a0f77-736c-8ad7-d795-62029e5b2efb',
    'relationship_name' => 'veta_requerimiento_created_by',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Veta_Requerimiento',
    'rhs_table' => 'veta_requerimiento',
    'rhs_key' => 'created_by',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'veta_requerimiento_assigned_user' => 
  array (
    'id' => '68840481-6440-c1a3-f074-62029e7d78f8',
    'relationship_name' => 'veta_requerimiento_assigned_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Veta_Requerimiento',
    'rhs_table' => 'veta_requerimiento',
    'rhs_key' => 'assigned_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'securitygroups_veta_requerimiento' => 
  array (
    'id' => '6d13092c-264b-59e5-ea06-62029e287480',
    'relationship_name' => 'securitygroups_veta_requerimiento',
    'lhs_module' => 'SecurityGroups',
    'lhs_table' => 'securitygroups',
    'lhs_key' => 'id',
    'rhs_module' => 'Veta_Requerimiento',
    'rhs_table' => 'veta_requerimiento',
    'rhs_key' => 'id',
    'join_table' => 'securitygroups_records',
    'join_key_lhs' => 'securitygroup_id',
    'join_key_rhs' => 'record_id',
    'relationship_type' => 'many-to-many',
    'relationship_role_column' => 'module',
    'relationship_role_column_value' => 'Veta_Requerimiento',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'veta_requerimiento_doc_comentarios_1' => 
  array (
    'rhs_label' => 'Documents Chat Notes',
    'lhs_label' => 'Requirements',
    'rhs_subpanel' => 'default',
    'lhs_module' => 'Veta_Requerimiento',
    'rhs_module' => 'Doc_Comentarios',
    'relationship_type' => 'one-to-many',
    'readonly' => true,
    'deleted' => false,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
    'relationship_name' => 'veta_requerimiento_doc_comentarios_1',
  ),
);